### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by pbishop11** [deco3500-2018/social-media#1]
What we need to do before next friday:
**Milestones**
- [ ] Finish Contract - Read over and approved by all members

- [ ] Read over meeting notes and confirm concept

- [ ] Start Proposal

- [ ] Delegate tasks/ sections of proposal

- [ ] Create slides ( Max 5)
